### ISSUE TITLE
Cannot open converted h5 file with read_h5 function.

### ISSUE THREAD

**Issue by errcricket** [JiekaiLab/scDIOR#1]
I am trying out your very needed conversion tool. 
```
import PyIOH5 as myh5
import scanpy as sc

# read the data from h5ad file
adata = sc.read(filename = '20210217_NasalSwab_Broad_BCH_UMMC_to_CZI.h5ad')
# save the data into the h5 file 
myh5.ouput.write_h5(adata=adata, file = '20210217_NasalSwab_Broad_BCH_UMMC_to_CZI_scampy.h5ad')
```

This was successful however, I should also point out that you use `file` instead of `filename` for the scanpy call and that you have `myh5.ouput.write_h5` instead of `myh5.output.write_h5`.

I then try to open the file in Seurat...

```
library(hdf5r, lib='/home/R_packages/R403')
library(Seurat, lib='/home/R_packages/R403')
library(RIOH5, lib='/home/R_packages/R403')
library(SingleCellExperiment)

data_seurat = read_h5(target.object = 'seurat', file = 'data/sample_data/20210217_NasalSwab_Broad_BCH_UMMC_to_CZI_scampy.h5ad')
```
Which causes this error:

```
Warning: No columnames present in cell embeddings, setting to 'PCA_1:100'
Warning: No columnames present in cell embeddings, setting to 'UMAP_1:2'
<simpleError in h5attr(h5mat, "datatype"): Attribute does not exist>
function (..., list = character(), package = NULL, lib.loc = NULL, verbose = getOption("verbose"), 
    envir = .GlobalEnv, overwrite = TRUE)  
Error in object[[i]] : object of type 'closure' is not subsettable
```

The original h5ad file comes from here: https://www.covid19cellatlas.org/index.patient.html. I don't know if the error is caused by the file formatting or by the scDIOR tool. I will say that I have been unsuccessful using _any_ tools to open these annotated files in Seurat so I am hoping your tool will work. Please advise.

**Comment by fenghuijian** [comment]
Hi
Thank you very much for using our software and for your comments. I'm really sorry for taking so long to reply to you. 
Now we have updated the software to the latest version and solve many bugs.
You need to re-update dior (R) and diopy (Python) of scDIOR, and then convert the data again.
 The using details can be viewed https://github.com/JiekaiLab/scDIOR (README). 
Please tell me, if you have any other questions when using the scDIOR

**Comment by fenghuijian** [comment]
Hi
I didn't get the alert on my email, so I'm sorry for the late reply. Could you tell me what are the objects of scanpy？ I guess that some attributes were missing which is causing the store to fail。And I debug at the same time。
