### ISSUE TITLE
h5ad convert seurat

### ISSUE THREAD

**Issue by wwh199459** [JiekaiLab/scDIOR#4]
Thanks for the package. An error occurred when running dior through R, h5ad to seurat.            

Error in seurat_read_h5(file = file, assay.name = assay.name) : 
  No such file or directory

##################################################################
library("dior")
setwd("")
adata_seurat = read_h5ad(file = 'data.h5ad', 
                          target.object = 'seurat', 
                          assay_name = 'RNA')

Error in seurat_read_h5(file = file, assay.name = assay.name) : 
  No such file or directory

**Comment by fenghuijian** [comment]
Thank you very much for using our software and for your comments. I'm really sorry for taking so long to reply to you.
This problem seems to be caused by the incorrect path of the input file, please confirm the path of the input file.
